feat: update claim command
filecoin-saturn/contracts pull request #73
Opened 2023-08-18 01:48 UTC by AmeanAsad

## Changes:
- Update DB queries for payment retrieval 
- Update the claim command to now query all releasable contracts for a given address and then now only query those contracts for payment releasing.

2023-08-22 15:27 UTC, patrickwoodhead requested changes

2023-08-22 15:27 UTC, patrickwoodhead commented on README.md
> +cargo run --bin saturn-contracts -- -S secrets/.secret -U https://api.calibration.node.glif.io/rpc/v1 --retries=10 deploy
Let's pull the changes from hyperspace to calibration into a different PR for clarity

2023-08-22 15:27 UTC, patrickwoodhead commented on cli/src/db.rs
> +        FROM  payments
Lets put this in another PR too

2023-08-22 17:51 UTC, AmeanAsad commented
@patrickwoodhead removed the unrelated changes from here

2023-08-23 11:01 UTC, patrickwoodhead approved these changes

2023-08-23 13:54 UTC, merged